### PR TITLE
fix: hijack_cursor with update_focused_file

### PR DESCRIPTION
**Pull request by geril2207**
Fix: #2599

### CODE REVIEW

**Comment by alex-courtis** [comment]
Unfortunately this doesn't always work. It seems the issue might be with `place_cursor_on_node`

[2599.log.patch.gz](https://github.com/nvim-tree/nvim-tree.lua/files/13767423/2599.log.patch.gz)

```
[2023-12-26 09:51:52] [dev] hijacking {
  buf = 2,
  event = "BufEnter",
  file = "/home/alex/src/linux/NvimTree_1",
  group = 8,
  id = 14,
  match = "/home/alex/src/linux/NvimTree_1"
}
[2023-12-26 09:51:52] [dev] place_cursor_on_node
[2023-12-26 09:51:52] [dev] hijacking {
  buf = 2,
  event = "CursorMoved",
  file = "/home/alex/src/linux/NvimTree_1",
  group = 8,
  id = 14,
  match = "/home/alex/src/linux/NvimTree_1"
}
[2023-12-26 09:51:52] [dev] place_cursor_on_node
...
[2023-12-26 09:52:00] [dev] hijacking {
  buf = 2,
  event = "CursorMoved",
  file = "/home/alex/src/linux/NvimTree_1",
  group = 8,
  id = 14,
  match = "/home/alex/src/linux/NvimTree_1"
}
[2023-12-26 09:52:00] [dev] place_cursor_on_node
[2023-12-26 09:52:00] [dev] nvim_win_set_cursor(0, { 35, 6 })
```

**Comment by alex-courtis** [comment]
It also looks like the `BufEnter` is redundant, as `CursorMoved` is documented to fire when moved to another window.

**Comment by geril2207** [comment]
> Unfortunately this doesn't always work. It seems the issue might be with `place_cursor_on_node`

I don't find any issues, but yeah, there are better ways to resolve.
Why do we need the following? Perf reasons? For me removing this check fixes the issue.
https://github.com/nvim-tree/nvim-tree.lua/blob/50f30bcd8c62ac4a83d133d738f268279f2c2ce2/lua/nvim-tree.lua#L117C2-L121

**Comment by alex-courtis** [comment]
> For me removing this check fixes the issue. Git blame says it was search fix, can you describe more about this? How can we change it. Actually it is, without this check you can't go next in search using `n` but can go prev with `N`. Seems that we need to find better way to handle if search with hijack_cursor.

That is very old code indeed, unfortunately I have no insight. It could be from a time when there was no root node or there was something else on the top line.

It's actually blocking hijack on the root node itself.

This is only called in one place and we can easily test it. Do you want to just rewrite that method? It's clear what it needs to do and can be very simple.

**Comment by geril2207** [comment]
> Correct me if I'm wrong, but it looks like we don't have any search n or N mappings or functionality, just a one off search and find.

I am about native neovim `/` or `?` search where you have native n and N binds for jump next/prev. I don't think we should break it. And with removing line check, we will break n bind completely, you can't jump to the next occurence if current one not on the start.

**Comment by alex-courtis** [comment]
> I am about native neovim `/` or `?` search where you have native n and N binds for jump next/prev. I don't think we should break it. And with removing line check, we will break n bind completely, you can't jump to the next occurence if current one not on the start.

Ah I see, I completely misunderstood. I was thinking about `S` search rather than reglar vim search. Yes, we should not break that.

This is quite tricky. The `prev_line` local is quite hacky and will break when switching nvim-tree windows / tabs etc.

Do you want to try writing a "clean" implementation? It seems clear what the requirements are now.

**Comment by geril2207** [comment]
> This is quite tricky. The prev_line local is quite hacky and will break when switching nvim-tree windows / tabs etc.
Do you want to try writing a "clean" implementation? It seems clear what the requirements are now.

I don't think we need completely rewrite impl, just to figure out how to handle search better. Any ideas, how to detect if search, or maybe detect params of text under cursor? Currently I have no way to solve it.

**Comment by alex-courtis** [comment]
> Any ideas, how to detect if search, or maybe detect params of text under cursor? Currently I have no way to solve it.

Ah yes, that would do it.

Looking at lualine it's using `hlsearch` and seems functional: https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/components/searchcount.lua

**Comment by geril2207** [comment]
My assumption is that we can get search entries through extmarks and if cursor under search extmark we skip hijacking.

**Comment by alex-courtis** [comment]
> My assumption is that we can get search entries through extmarks and if cursor under search extmark we skip hijacking.

Yes please... that will inform us whether we are searching inside the nvim-tree window AND we are on the match.

**Comment by geril2207** [comment]
Seems that we can't do that with extmarks. I checked `vim.fn.searchcount` and seems that we can use `exact_match` from the result. From my tests, if cursor under search word `exact_match` eq to 1. In this case we can skip hijacking. I can do rewrite with `vim.fn.searchcount` but not now.

**Comment by geril2207** [comment]
So what do you think about current solution?

**Comment by alex-courtis** [comment]
> So what do you think about current solution?

Well, that's rather elegant. Cursor is always correctly placed on n/N and is hijacked on j/k
* `update_focused_file` T/F
* `hijack_cursor` T/F
* `&wrapscan` on/off
* `root_folder_label = false`

Regression: user can't move horizontally on a node with h/l.
Looking at the documentation "Keeps the cursor on the first letter of the filename when moving in the tree."
I'm happy to run with this new behaviour - it matches the documentation.

**Review by alex-courtis — APPROVED** [review]
Fantastic work as always @geril2207

**Pull request merged**
