### PR TITLE
fix(#2086): fix api.fs.rename_sub doesn't remove previous filename anymore

### PR DESCRIPTION
**Pull request by pholawat-tle**
fix issue #2086 

Replace `:p` modifier with `:p:h` to replicate behavior prior to the bug
Reference: https://vimhelp.org/cmdline.txt.html#filename-modifiers

### Before

image

### After
image

### CODE REVIEW

**Review by alex-courtis — APPROVED** [review]
This works nicely, many thanks for your contribution.

It matches the mapping description "Rename: Omit Filename"

**Comment by pholawat-tle** [comment]
> So how do I set the setting to get the previous filename?
> 
> ```lua
>                     vim.keymap.set('n', 'e', api.fs.rename_sub, opts('Rename: Absolute Path'))
> ```

Do `vim.keymap.set("n", "r", api.fs.rename, opts("Rename"))`

**Comment by aemonge** [comment]
Can it get mixed with Absolute Path?

It was pretty useful to simple edit the path, to move it to another directory.

**Comment by alex-courtis** [comment]
> Can it get mixed with Absolute Path?

See #2148

**Pull request merged**
