### PR TITLE
fix(git): git watcher showing error for bare repositories

### PR DESCRIPTION
**Pull request by Deshdeepak1**
use absolutegitdir for watcher instead of toplevel

toplevel/.git and  git dir are same  for non bare repositories. But for bare repositories it was showing error.

### CODE REVIEW

**Comment by alex-courtis** [comment]
Unfortunately my git knowledge is insufficient to understand the use case for operating inside a bare repo.

Perhaps you could provide me with an example I can replicate locally to test this out.

**Review by kylo252 — COMMENTED** [review]
Some additional notes:
- should probably use the `git.runner` module
- should probably handle `GIT_DIR` and `GIT_WORK_TREE`
- bumping the requirement to neovim v0.8 will allow using `vim.fs` which has a few useful functions for normalizing paths.

**Comment by alex-courtis** [comment]
> * bumping the requirement to neovim v0.8 will allow using `vim.fs` which has a few useful functions for normalizing paths.

0.8.0 was released ~Oct 2022

I think it's time.

@gegoune ?

**Comment by gegoune** [comment]
Many other popular plugins did that already. It is time.

**Comment by alex-courtis** [comment]
@kylo252 you should have permissions to approve/reject/need-work PRs.

Your reviews are gratefully appreciated :)

**Comment by alex-courtis** [comment]
> Many other popular plugins did that already. It is time.

Done cdb40dc

Feels good to remove workarounds...

**Review by alex-courtis — CHANGES_REQUESTED** [review]
https://github.com/nvim-tree/nvim-tree.lua/pull/1809 has been merged; please merge master.

**Comment by alex-courtis** [comment]
Any progress on this one @Deshdeepak1 ?

**Pull request closed without merging**
