### PR TITLE
fix(#1815): don't schedule find file calls

### LINKED ISSUE #1815: Telescope `find_files` Fails `update_focused_file`
### Description

Focused file is not updated following telescope find file when git is enabled.

### Neovim version

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.0.11-arch1-1

### nvim-tree version

f8489c9

### Minimal config

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-dev/site]]
local package_root = "/tmp/nvt-dev/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "/home/alex/.local/share/nvim/vundle/nvim-tree.lua.dev",
      "nvim-tree/nvim-web-devicons",
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope-fzf-native.nvim',
      'nvim-telescope/telescope.nvim',
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup({
    auto_reload_on_write = true,
    create_in_closed_folder = false,
    disable_netrw = false,
    hijack_cursor = false,
    hijack_netrw = true,
    hijack_unnamed_buffer_when_opening = false,
    ignore_buffer_on_setup = false,
    open_on_setup = false,
    open_on_setup_file = false,
    sort_by = "name",
    root_dirs = {},
    prefer_startup_root = false,
    sync_root_with_cwd = false,
    reload_on_bufenter = false,
    respect_buf_cwd = false,
    on_attach = "disable",
    remove_keymaps = false,
    select_prompts = false,
    view = {
      adaptive_size = false,
      centralize_selection = false,
      width = 30,
      hide_root_folder = false,
      side = "left",
      preserve_window_proportions = false,
      number = false,
      relativenumber = false,
      signcolumn = "yes",
      mappings = {
        custom_only = false,
        list = {
          -- user mappings go here
        },
      },
      float = {
        enable = false,
        quit_on_focus_loss = true,
        open_win_config = {
          relative = "editor",
          border = "rounded",
          width = 30,
          height = 30,
          row = 1,
          col = 1,
        },
      },
    },
    renderer = {
      add_trailing = false,
      group_empty = false,
      highlight_git = false,
      full_name = false,
      highlight_opened_files = "none",
      root_folder_label = ":~:s?$?/..?",
      indent_width = 2,
      indent_markers = {
        enable = false,
        inline_arrows = true,
        icons = {
          corner = "└",
          edge = "│",
          item = "│",
          bottom = "─",
          none = " ",
        },
      },
      icons = {
        webdev_colors = true,
        git_placement = "before",
        padding = " ",
        symlink_arrow = " ➛ ",
        show = {
          file = true,
          folder = true,
          folder_arrow = true,
          git = true,
        },
        glyphs = {
          default = "",
          symlink = "",
          bookmark = "",
          folder = {
            arrow_closed = "",
            arrow_open = "",
            default = "",
            open = "",
            empty = "",
            empty_open = "",
            symlink = "",
            symlink_open = "",
          },
          git = {
            unstaged = "✗",
            staged = "✓",
            unmerged = "",
            renamed = "➜",
            untracked = "★",
            deleted = "",
            ignored = "◌",
          },
        },
      },
      special_files = { "Cargo.toml", "Makefile", "README.md", "readme.md" },
      symlink_destination = true,
    },
    hijack_directories = {
      enable = true,
      auto_open = true,
    },
    update_focused_file = {
      enable = true,
      update_root = false,
      ignore_list = {},
    },
    ignore_ft_on_setup = {},
    system_open = {
      cmd = "",
      args = {},
    },
    diagnostics = {
      enable = false,
      show_on_dirs = false,
      show_on_open_dirs = true,
      debounce_delay = 50,
      severity = {
        min = vim.diagnostic.severity.HINT,
        max = vim.diagnostic.severity.ERROR,
      },
      icons = {
        hint = "",
        info = "",
        warning = "",
        error = "",
      },
    },
    filters = {
      dotfiles = false,
      custom = {},
      exclude = {},
    },
    filesystem_watchers = {
      enable = true,
      debounce_delay = 50,
      ignore_dirs = {},
    },
    git = {
      enable = true,
      ignore = true,
      show_on_dirs = true,
      show_on_open_dirs = true,
      timeout = 400,
    },
    actions = {
      use_system_clipboard = true,
      change_dir = {
        enable = true,
        global = false,
        restrict_above_cwd = false,
      },
      expand_all = {
        max_folder_discovery = 300,
        exclude = {},
      },
      file_popup = {
        open_win_config = {
          col = 1,
          row = 1,
          relative = "cursor",
          border = "shadow",
          style = "minimal",
        },
      },
      open_file = {
        quit_on_open = false,
        resize_window = true,
        window_picker = {
          enable = true,
          chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
          exclude = {
            filetype = { "notify", "packer", "qf", "diff", "fugitive", "fugitiveblame" },
            buftype = { "nofile", "terminal", "help" },
          },
        },
      },
      remove_file = {
        close_window = true,
      },
    },
    trash = {
      cmd = "gio trash",
      require_confirm = true,
    },
    live_filter = {
      prefix = "[FILTER]: ",
      always_show_folders = true,
    },
    tab = {
      sync = {
        open = false,
        close = false,
        ignore = {},
      },
    },
    notify = {
      threshold = vim.log.levels.INFO,
    },
    log = {
      enable = true,
      truncate = true,
      types = {
        all = false,
        config = false,
        copy_paste = false,
        dev = true,
        diagnostics = false,
        git = false,
        profile = false,
        watcher = false,
      },
    },
  })

  local nt_api = require("nvim-tree.api")

  vim.keymap.set("n", ";", ":", { noremap = true })
  vim.keymap.set("n", "<space>a", nt_api.tree.open, { noremap = true })
  vim.keymap.set("n", "<space>o", [[ :wincmd p<CR> ]], { noremap = true })
  vim.keymap.set("n", "<space>i", require('telescope.builtin').buffers, { noremap = true })
  vim.keymap.set("n", "<bs>f", require('telescope.builtin').find_files, { noremap = true })
end
```

### Steps to reproduce

```
touch a b
git init
```

```
:NvimTreeOpen
:wincmd p
:find a
:find b
:ls!
  1 #h   "a"                            line 1
  2u a-  "NvimTree_1"                   line 0
  3 %a   "b"                            line 1
```

```
:NvimTreeOpen
:lua require('telescope.builtin').find_files (a)
:lua require('telescope.builtin').find_files (b)
:ls!
  1 #h   "a"                            line 1
  2u a-  "NvimTree_1"                   line 0
 18 %a   "b"                            line 1
```

### Expected behavior

b focused

### Actual behavior

a focused for telescope case

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #1815 

Optimistic PR for dogfooding.

Both
https://github.com/nvim-tree/nvim-tree.lua/pull/1820/files#diff-d2d7203cea884a09928ac1574693d436d6e3db28e62daabfa53f5f9f7740f51aR157 and

https://github.com/nvim-tree/nvim-tree.lua/blob/b17358ff4d822deeb42b97919065800f8f91cb55/lua/nvim-tree/actions/finders/find-file.lua#L21

protect against any finding of buffers that are not real files i.e. not nvim-tree itself.

### CODE REVIEW

**Comment by gegoune** [comment]
Functionally it works, thanks for the fix!

But not exporting `find_file()` will break for users using it. I am not sure if it ever was meant to be used and given we have an api we should make it the only 'entry' point to nvim-tree (programatically).

Should equivalent be:
```lua
      require('nvim-tree').open()
      require('nvim-tree.api').tree.find_file(bufname)
```
?

**Review by gegoune — APPROVED** [review]

**Comment by alex-courtis** [comment]
> But not exporting `find_file()` will break for users using it. I am not sure if it ever was meant to be used and given we have an api we should make it the only 'entry' point to nvim-tree (programatically).

Ah of course, I wondered why it was public.

There's `api.tree.find_file`, `api.tree.toggle`, `:NvimTreeFindFile` and `:NvimTreeFindFileToggle`

I'm game to remove it if you are ;)

**Comment by alex-courtis** [comment]
Quick BufEnter events cause multiple find_file calls, which is a performance hit as it results in an FS and git refresh.

Debounced all events with single context `"BufEnter:find_file"`.

**Comment by gegoune** [comment]
Absolutely, remove it. Even if it was not intended to be used I think that removal warrants notifying users? It will be breaking change for sure.

**Comment by alex-courtis** [comment]
> Even if it was not intended to be used I think that removal warrants notifying users?

https://github.com/nvim-tree/nvim-tree.lua/pull/1820/commits/a2840619b48055cae55c7cf1bdcd30f1c9bf5d6a

**Pull request merged**
