### PR TITLE
chore(#2787): minimum nvim version 0.9, replace 0.10 deprecated, enable deprecated warnings

### LINKED ISSUE #2787: enable deprecated warnings, minimum neovim version 0.9, harden support for greater versions
API changed many times during the 0.10 dev cycle. Many users are using various versions of 0.10 pre-release. We must ensure that the correct functions are being used. Resolves issues such as https://github.com/nvim-tree/nvim-tree.lua/pull/2781#issuecomment-2131372538

We can use a lazily loaded cache of supported API. Requires minimum nvim version of 0.9

Testing `:h api-level`
```lua
local log = require "amc.log"

local api_info = vim.fn.api_info()

log.line("version %s", vim.inspect(api_info.version))
log.line("ui_options %s", vim.inspect(api_info.ui_options))

for _, v in ipairs(api_info.functions) do
  if v.deprecated_since and v.deprecated_since ~= 1 then
    log.line("%s %s %s", v.name, vim.inspect(v.since), vim.inspect(v.deprecated_since))
  end
end
```

0.9.5
```
version {
  api_compatible = 0,
  api_level = 11,
  api_prerelease = false,
  major = 0,
  minor = 9,
  patch = 5,
  prerelease = false
}

nvim_exec 7 11
nvim_command_output 1 7
nvim_execute_lua 3 7
nvim_buf_get_number 1 2
nvim_buf_clear_highlight 1 7
nvim_buf_set_virtual_text 5 8
nvim_get_hl_by_id 3 9
nvim_get_hl_by_name 3 9
```

0.10.0
```
version {
  api_compatible = 0,
  api_level = 12,
  api_prerelease = vim.NIL,
  build = vim.NIL,
  major = 0,
  minor = 10,
  patch = 0,
  prerelease = true
}
nvim_exec 7 11
nvim_command_output 1 7
nvim_execute_lua 3 7
nvim_buf_get_number 1 2
nvim_buf_clear_highlight 1 7
nvim_buf_set_virtual_text 5 8
nvim_get_hl_by_id 3 9
nvim_get_hl_by_name 3 9
nvim_get_option_info 7 11
nvim_set_option 1 11
nvim_get_option 1 11
nvim_buf_get_option 1 11
nvim_buf_set_option 1 11
nvim_win_get_option 1 11
nvim_win_set_option 1 11
nvim_call_atomic 1 12
```

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #2787 

- [ ] tag `compat-nvim-0.8`

### CODE REVIEW

**Comment by ZacharyRizer** [comment]
What needs to be done to get this merged @alex-courtis? I'd love to get that warning to go away every time nvim starts up on 0.10

**Comment by alex-courtis** [comment]
> What needs to be done to get this merged @alex-courtis? I'd love to get that warning to go away every time nvim starts up on 0.10

Test please!

How are you seeing the warning? I didn't know nvim could do that...

**Comment by ZacharyRizer** [comment]
Maybe I misunderstood the point of this PR. I thought this was to fix the same issue that I tried to fix in this PR: https://github.com/nvim-tree/nvim-tree.lua/pull/2781 which was then reverted back. My pr fixed this error from showing on start or 0.10 and 0.9 users (I thought at least). 

image

But that message has come back since the above PR was reverted. Is this PR intended to fix the same issue?

**Comment by alex-courtis** [comment]
> Maybe I misunderstood the point of this PR. I thought this was to fix the same issue that I tried to fix in this PR: #2781 which was then reverted back. My pr fixed this error from showing on start or 0.10 and 0.9 users (I thought at least).

Yes, I had to revert that one as it broke [0.10 dev versions](https://github.com/nvim-tree/nvim-tree.lua/blob/e026466e77e3a5383b717feb2bb44da7b57dfdfc/lua/nvim-tree/diagnostics.lua#L43). That method was added / mutated during the dev cycle.

It's the only vim api like that, all others were updated to use the new. We could do something like testing whether `is_enabled` is a function and use that only when 0.10 and the function is present.

> But that message has come back since the above PR was reverted. Is this PR intended to fix the same issue?

Yes! That's what I'm after - how do you run that?

`:checkhealth vim.deprecated` yields:
```

==============================================================================
vim/deprecated: 

- ERROR No healthcheck found for "vim/deprecated" plugin.
```

**Comment by alex-courtis** [comment]
I've reinstated #2781 with an extra test: https://github.com/nvim-tree/nvim-tree.lua/pull/2788/commits/46c2fb63f102443399a3e819d263226acdd856b9

Please let me know how that goes.

**Comment by alex-courtis** [comment]
@ZacharyRizer I've not forgotten about you. We will get to the bottom of this:

* How are you running that deprecated health check?
* Why does it only pick up that one deprecated, not the other 26?

**Pull request merged**
