### PR TITLE
feat: add normal nc highlight group

### LINKED ISSUE #704: Dim nvim-tree when inactive
Hello,
first of all, this plugin is great :)

I have the following configuration to dim inactive panes:

```
vim.cmd([[
	hi ActiveWindow guibg=#191919
	hi InactiveWindow guibg=#282828
]])

vim.o.winhighlight = "Normal:ActiveWindow,NormalNC:InactiveWindow"
```
So I was wondering if it would possible to support NormalNC in this plugin so it dims automatically.

Thanks for this great plugin :)

### PR DESCRIPTION
**Pull request by kyazdani42**
closes #704

### CODE REVIEW

**Comment by mortezadadgar** [comment]
> should be fixed in [22e64cc](https://github.com/kyazdani42/nvim-tree.lua/commit/22e64cc73624a91871a401d479c6f315e1d7b943) (1.5.13) If it still appears you can override the `NvimTreeSignColumn` color group to link to to `Normal`

Thanks! linked `NvimTreeSignColumn`

**Comment by siduck76** [comment]
@kyazdani42 how do I disable the dim? I tried using NvimTreeNormalNC's guibg as the same as NvimTreeNormal but didnt work :/

**Comment by kyazdani42** [comment]
something like `hi! NvimTreeNormalNC guibg=hex_code` should work normally

**Comment by mortezadadgar** [comment]
@siduck76 try this `hi link NvimTreeSignColumn NvimTreeNormal`

**Comment by kyazdani42** [comment]
might be due to an ordering issue, highlights sometimes are being erased. try putting this in your colorscheme file

**Comment by gegoune** [comment]
Is it possible to completely disable this feature? It shows different SignColumn (to Normal) when active. They are the same when inactive.

**Comment by siduck76** [comment]
> might be due to an ordering issue, highlights sometimes are being erased. try putting this in your colorscheme file

I tried it , didnt work out :/

**Comment by smartding** [comment]
@siduck76 

`highlight! link NvimTreeSignColumn Normal` works for me.

**Comment by siduck76** [comment]
@smartding

https://user-images.githubusercontent.com/59060246/136679047-cfb4140c-b4b9-4f01-9edb-df3918efadda.mp4

Doesnt work for me at all :/ 

tried using a minimal config 

https://paste.sh/2mF-joZM#ZiOcbqstl6aTG0AlCkAZmKDX

**Comment by siduck76** [comment]
@smartding didnt work , NvimTreeNormalNC works

**Comment by kyazdani42** [comment]
a temporary solution otherwise if you cannot manage to change the colors would be to change the winhl value in the winopts.
```lua
require'nvim-tree.view'.View.winopts.winhl =  table.concat({
      'EndOfBuffer:NvimTreeEndOfBuffer',
      'Normal:NvimTreeNormal',
      'CursorLine:NvimTreeCursorLine',
      'VertSplit:NvimTreeVertSplit',
      'StatusLine:NvimTreeStatusLine',
      'StatusLineNC:NvimTreeStatuslineNC',
      'SignColumn:NvimTreeSignColumn', -- just remove this line
      'NormalNC:NvimTreeNormalNC', -- and this line
    },
```

**Comment by dbarrosop** [comment]
@kyazdani42 I actually solved by emptying the list:

```
    require'nvim-tree.view'.View.winopts.winhl = table.concat({})
```

It works and I don't require to set links or extra configuration. Assuming I don't want specific highlights for this plugin, os there any reason why I wouldn't do that? If that works and there is nothing wrong with it, maybe it could be an option you can pass to `setup`.

Thanks again for looking into this :)

**Pull request merged**
