### PR TITLE
feat(event): add WillCreateFile, WillRemoveFile

### PR DESCRIPTION
**Pull request by asmodeus812**
Add new will-action events to complement the existing one for rename node. These are mostly going to be useful for implementing lsp file operation actions.

### CODE REVIEW

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Works nicely, thank you.

- [ ] Please add these to :help

**Comment by alex-courtis** [comment]
It would be great if you could work with @antosha417 and integrate these events into the [nvim-lsp-file-operations](https://github.com/antosha417/nvim-lsp-file-operations) plugin.

**Comment by asmodeus812** [comment]
@alex-courtis I have resolved the conflicts and updated the docs

**Review by alex-courtis — APPROVED** [review]
Many thanks for your contribution!

**Pull request merged**
