### PR TITLE
ci: luarocks releases

### PR DESCRIPTION
**Pull request by insipx**
Hey 👋
 
 ### Summary
 This PR is part of a push to get neovim plugins on [LuaRocks](https://luarocks.org/labels/neovim).
 
 See also:
 
 * [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim), a new luarocks-based plugin manager.
 * [this blog post](https://mrcjkb.github.io/posts/2023-01-10-luarocks-tag-release.html).
 
 With luarocks/rocks.nvim, it is [the plugin authors' responsibility to declare dependencies - not the user's](https://github.com/nvim-neorocks/rocks.nvim?tab=readme-ov-file#grey_question-why-rocksnvim). Installing this plugin is as simple as `:Rocks install nvim-tree.lua`.
 
 ### Things done:
 * Add a workflow that publishes tags to luarocks.org when a tag or release is pushed.
 
 ### Notes:
 > [!IMPORTANT]
 > **For the luarocks workflow to work, someone with a luarocks.org account will have to add their [API key](https://luarocks.org/settings/api-keys) to this repo's [GitHub actions secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)**.
 
 * Tagged releases are installed locally and then published to luarocks.org.
   
   * If you push tags from a local checkout, the workflow is triggered automatically.
   * If you use GitHub releases to create tags, you may need to [add a PA token](https://github.com/nvim-neorocks/sample-luarocks-plugin?tab=readme-ov-file#generating-a-pat-personal-access-token) for the workflow to be triggered automatically.
 * Due to a shortcoming in LuaRocks ([label doesn't get picked up from rockspec luarocks/luarocks-site#188](https://github.com/luarocks/luarocks-site/issues/188)), the `neovim` and/or `vim` labels have to be added  to the LuaRocks package manually (after the first upload), for this plugin to show up in https://luarocks.org/labels/neovim or https://luarocks.org/labels/vim, respectively.
 
 See also [this guide](https://github.com/vhyrro/sample-luarocks-plugin).

### CODE REVIEW

**Comment by alex-courtis** [comment]
This looks fantastic! We have the same process for nvim-webdevicons

Can I please ask you to refactor this to have the same layout/style as https://github.com/nvim-tree/nvim-web-devicons/blob/master/.github/workflows/release.yml

The key difference is the `v*` version tag; we don't want all master changes published.

**Comment by alex-courtis** [comment]
> **For the luarocks workflow to work, someone with a luarocks.org account will have to add their [API key](https://luarocks.org/settings/api-keys) to this repo's [GitHub actions secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)**.

We have a key for the [nvim-tree organisation](https://luarocks.org/modules/nvim-tree) - am I correct in assuming we can use that here?

> the neovim and/or vim labels have to be added to the LuaRocks package manually

Yup, hit that one :)

> rocks.nvim, a new luarocks-based plugin manager.

I like this.

**Comment by alex-courtis** [comment]
v1.3.2 is ready to release: https://github.com/nvim-tree/nvim-tree.lua/pull/2761

We han hold it back if we get luarocks release ready soon.

**Comment by insipx** [comment]
Hey! Sorry i've been delayed, just moved houses, i'll make sure to refactor to the same layout to get this ready for merge :)

**Comment by insipx** [comment]
> We have a key for the [nvim-tree organisation](https://luarocks.org/modules/nvim-tree) - am I correct in assuming we can use that here?

Yep, this should work!

**Comment by alex-courtis** [comment]
Fantastic, many thanks!

Before I pull the trigger there is a tag issue to resolve:  nvim-tree uses release please, which generates multiple SEMVER tags e.g.
```
* 76db7ed (tag: v1.3, tag: v1, tag: nvim-tree-v1.3.1) chore(master): release nvim-tree 1.3.1 (#2736)  github-actions[bot]  Tue Apr 30 11:12
```

The first release will be successful and all 3 tags will be pushed. Unfortunately the next release will reject the updated `v1` and `v1.3` tags as they are already present.

See latest nvim-web-devicons luarocks release exhibiting this reject for `v0`: https://github.com/nvim-tree/nvim-web-devicons/actions/runs/9041343035

What should do here? Some thoughts:
1. force push like `luarocks upload --force`
2. only use full SEMVER tags like `v1.3.1`
3. delete `v1.3` before pushing

Please tell us the "correct" way of handling these tags.

**Comment by alex-courtis** [comment]
In the interests of speed, I've restricted the versions to full SEMVER `'v[0-9]+.[0-9]+.[0-9]+'`. We can add major and major minor in the future if we need them.

Worked beautifully, many thanks @insipx !

https://luarocks.org/modules/nvim-tree/nvim-tree.lua

**Comment by alex-courtis** [comment]
One last question @insipx :

I see the `neorocks` organisation. `nvim-tree.lua` is owned by the `nvim-tree` organisation instead of `neorocks`.

Should nvim-tree be part of neorocks?

**Comment by insipx** [comment]
Don't think so, I as able to `Rocks install nvim-tree.lua` using the rocks plugin for neovim, so it seems everything is working as intended!

Thanks for adding those extra commits! Glad this is now packaged :)

**Comment by alex-courtis** [comment]
> @alex-courtis Don't think so, I as able to `Rocks install nvim-tree.lua` using the rocks plugin for neovim, so it seems everything is working as intended!
> 
> Thanks for adding those extra commits! Glad this is now packaged :)

Great news, thanks for getting all this together.

**Pull request merged**
