### PR TITLE
ci: configure release-please

### PR DESCRIPTION
**Pull request by gegoune**
Release-As: 0.9.0

### CODE REVIEW

**Review by alex-courtis — APPROVED** [review]
Nice. How do we do this? Add a tag?

**Comment by gegoune** [comment]
If I did everything correctly that PR, once merged, should trigger release-please to open new PR for version 0.9.0. No need to tag anything manually if we keep `Release-As: 0.9.0` in merge commit.

**Comment by alex-courtis** [comment]
> If I did everything correctly that PR, once merged, should trigger release-please to open new PR for version 0.9.0. No need to tag anything manually if we keep `Release-As: 0.9.0` in merge commit.

This is great! Sounds like it will be a smooth process.

**Comment by gegoune** [comment]
Will see about that. :)
Will also require undoing https://github.com/nvim-tree/nvim-tree.lua/pull/2579#issuecomment-1848022674.

**Comment by alex-courtis** [comment]
Pull the trigger?

**Pull request merged**
