### PR TITLE
fix(api): `find_file` doesn't work when `group_empty` option is enabled

### PR DESCRIPTION
**Pull request by liljaylj**

### CODE REVIEW

**Comment by alex-courtis** [comment]
Thanks for the PR @liljaylj 

I'm not able to replicate this - what exactly is the problem?

Perhaps you could raise a bug report with a [clean room replicator](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication) that demonstrates the problem.

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Before testing this fix a replicator is needed.

**Comment by liljaylj** [comment]
hello, created related issue

@alex-courtis  #2154

**Review by alex-courtis — APPROVED** [review]
This works nicely.

This affects core functionality; I'm going to dogfood for a week.

**Review by alex-courtis — APPROVED** [review]
Worked for a week. Many thanks for your contribution!

**Pull request merged**
