### PR TITLE
fix(#2643): correctly apply linked highlight groups in tree window

### LINKED ISSUE #2643: after #2415 NonText and WinSeparator have no highlight
### Description

obrazek

you can also see the weird `^^^^` in my statusline that appear only whenever I enter the NvimTree window (I have `laststatus=3`)

### Neovim version

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```

### Operating system and version

Linux IP5Pro 6.7.0-arch3-1 #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000 x86_64 GNU/Linux

### Windows variant

_No response_

### nvim-tree version

e9c5abe073a973f54d3ca10bfe30f253569f4405

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd 'hi link WinSeparator LineNr'

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end

-- UNCOMMENT this block for diagnostics issues, substituting pattern and cmd as appropriate.
-- Requires diagnostics.enable = true in setup.
--[[
vim.api.nvim_create_autocmd("FileType", {
  pattern = "lua",
  callback = function()
    vim.lsp.start { cmd = { "lua-language-server" } }
  end,
})
]]
```

### Steps to reproduce

open with the provided minimal config (or any config really) and `:NvimTreeOpen` and `:vsplit`.

### Expected behavior

WinSeparator and NonText highlights are consistent across windows

### Actual behavior

they are not highlighted at all

### LINKED ISSUE #2651: LineNrAbove/Below Not Applying LineNr
### Discussed in https://github.com/nvim-tree/nvim-tree.lua/discussions/2640

<div type='discussions-op-text'>

<sup>Originally posted by **TroySigX** January 23, 2024</sup>
Before this commit e9c5abe073a973f54d3ca10bfe30f253569f4405, my column for relative number (left-most column) will look like this:
image

But after, it look like this:
image

How can I change the color of the this column to be like before?

P.S: I'm using tokyonight.nvim colorscheme
</div>

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #2643
fixes #2651

Reverts to `&winhl` instead of a highlight namespace for the nvim-tree window. See #2634 comments for details on issues encountered.

- [x] TODO: reapply combined highlights on colorscheme change

### CODE REVIEW

**Comment by alex-courtis** [comment]
@petobens this is a more complete solution than #2652  which you tested. I'd be most grateful if you could test this one.

@JosefLitos and @TroySigX  I'd be most grateful for your testing this fix.

I'd be grateful if you could apply some changes to groups like `WinSeparator`, `VertSplit` and `NvimTreeWinSeparator` after you've opened the tree.

Bonus points for changing color schemes ;)

```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 2643-back-to-winhl
```

When you're finished testing:
```sh
git checkout master
```

**Comment by TroySigX** [comment]
This fixes my problem as well, but how do I change those groups you mentioned?

**Comment by JosefLitos** [comment]
I can also confirm this fixes all my issues - `NonText` and `WinSeparator` are both highlighted as expected and statusline shows no odd behaviour.

**Comment by petobens** [comment]
Works for me too. Thanks!

**Comment by alex-courtis** [comment]
> This fixes my problem as well, but how do I change those groups you mentioned?

Many thanks all!

You could change the groups before nvim-tree setup using something like:
```lua
vim.cmd([[
:hi WinSeparator guifg=blue
:hi NonText guifg=yellow
:hi LineNrAbove guifg=red
]])
```

When running you can enter the same commands to see "live updates".

**Pull request merged**
