### PR TITLE
docs: add nvim-tree-netrw

### PR DESCRIPTION
**Pull request by alex-courtis**
replaces #2200

### CODE REVIEW

**Review by gegoune — APPROVED** [review]
Better than readme. But perhaps let's link to it from readme?

**Comment by howarddo2208** [comment]
yeah, I think there need to be something in readme, beginners like me won't dig deep at first.

**Comment by alex-courtis** [comment]
Readme link is a good idea. Needs #2221 but I can at least get _a_ link in there for now.

**Review by gegoune — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
