### PR TITLE
refactor(#1645): remove unused open_replacing_current_buffer

### PR DESCRIPTION
**Pull request by alex-courtis**
discovered via #1645

### CODE REVIEW

**Comment by sharkov63** [comment]
lmao, this broke my config since I mapped `open_replacing_current_buffer` on my key. Is there any quick workaround to get the same functionality?

**Comment by alex-courtis** [comment]
See `:help nvim-tree-api.node.open.replace_tree_buffer`

**Comment by steliyan** [comment]
My workflow is broken as well, but currently, I don't believe it's supported.

1. Open a file
2. Use `open_replacing_current_buffer` (now removed)
3. Nvim-tree opens in the current buffer
4. Select a new file
5. Press ENTER
6. The new file is opened

Step 3 is not supported. What is described in the docs is step 4 onwards, but this re-arranges the windows in neovim which is not great.

If `NvimTreeFindFile` can use the current window, this will cover my (and probably @sharkov63 ) use cases.

**Comment by javiertury** [comment]
I'm on the same boat as @sharkov63 and @steliyan, but I have to agree that the maintenance burden may not be worth it.

The function `open_replacing_current_buffer` was introduced into nvim-tree as an utility (particularly useful for those who want to make nvim-tree behave more like netrw), so the workaround is simply to re-define the function ourselves:

```lua
local view = require "nvim-tree.view"
local core = require "nvim-tree.core"

local function openReplacingCurrentBuffer(cwd)
  if view.is_visible() then
    return
  end

  local buf = vim.api.nvim_get_current_buf()
  local bufname = vim.api.nvim_buf_get_name(buf)

  if bufname == "" or vim.loop.fs_stat(bufname) == nil then
    return
  end

  if cwd == "" or cwd == nil then
    cwd = vim.fn.fnamemodify(bufname, ":p:h")
  end

  if not core.get_explorer() or cwd ~= core.get_cwd() then
    core.init(cwd)
  end
  view.open_in_win { hijack_current_buf = false, resize = false }
  require("nvim-tree.renderer").draw()
  require("nvim-tree.actions.finders.find-file").fn(bufname)
end

-- Then use it for whatever purpose you see fit, for instance reimplementing netrw functionality

local function openInPlace(cwd)
  if cwd == "" or cwd == nil then
    local buf = vim.api.nvim_get_current_buf()
    local bufname = vim.api.nvim_buf_get_name(buf)

    if bufname ~= "" and vim.loop.fs_stat(bufname) ~= nil then
      cwd = vim.fn.fnamemodify(bufname, ":p:h")
    else
      cwd = vim.loop.cwd()
    end
  end

  openReplacingCurrentBuffer(cwd)
end

--
-- Commands
--

vim.api.nvim_create_user_command("Explore", function(res)
  openInPlace(res.args)
end, {
  desc = 'Open file explorer in current buffer',
  nargs = "?", complete = "dir"
})
```

**Comment by gegoune** [comment]
And why wouldn't you use provided api (https://github.com/nvim-tree/nvim-tree.lua/pull/2570#issuecomment-1862094961)?

**Comment by javiertury** [comment]
@gegoune, that api function doesn't seem to work for my usecase. It requires `nvim-tree` to already be present in the buffer, and when you call `replace_tree_buffer`, it opens the selected file in the same buffer.

My goal is to replicate netrw functionality. I want to open a nvim-tree window even if it didn't exist and use the provided argument as the working directory for `nvim-tree`. But I don't want to open any file.

**Comment by gegoune** [comment]
You can use `:h nvim-tree-api.tree.open()` for that.

**Comment by javiertury** [comment]
Thank you @gegoune, that is exactly what I needed!

**Comment by sharkov63** [comment]
> You can use `:h nvim-tree-api.tree.open()` for that.

This is what I was looking for, thank you very much!

**Pull request merged**
