### PR TITLE
feat: add api.marks.bulk.trash

### PR DESCRIPTION
**Pull request by pr4th4m**
### API to trash bulk files using external trash cli or similar

**Tested with**

OS: MacOS Ventura

CLI:

1. https://hasseg.org/trash/
    - This CLI has "put back" option on macos but needs a flag to be added in nvim-tree configure
    ```lua
     trash = {
        cmd = "trash -F",
     },
     ```
3. https://github.com/sindresorhus/trash-cli 
    - This CLI doesn't have "put back" option on macos https://github.com/sindresorhus/trash/issues/24, so I recommend using above CLI

**Keybinding:**

Add below keybinding to trash bulk files
```lua
vim.keymap.set('n', 'bt',    api.marks.bulk.trash,                  opts('Trash Bookmarked'))
```

### CODE REVIEW

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Many thanks for your contribution. We do need some work:

- [x] remove unnecessary refresh
- [x] handle `ui.confirm.trash = false`

**Testing:**
**OK:**
mark and trash files and folders - y
mark and trash - n
mark and trash - rubbish trash.cmd
nothing marked
`filesystem_watchers.enable = false`
Event.WillRemoveFile
Event.FileRemoved
Event.FolderRemoved
**Fail:**
`ui.confirm.trash = false` - doesn't prompt

**Comment by alex-courtis** [comment]
Many thanks for this one; trash is a useful feature.

**Comment by alex-courtis** [comment]
> `ui.confirm.trash = false` config should not prompt user, isn't it?
> I think this works as expected in nvim

It is indeed working as expected. I cannot recall my thought process there. Please accept my apologies.

Re-tested a subset - it's all looking good.

**Review by alex-courtis — APPROVED** [review]
Works beautifully, many thanks for your contribution!

**Comment by pr4th4m** [comment]
> > `ui.confirm.trash = false` config should not prompt user, isn't it?
> > I think this works as expected in nvim
> 
> It is indeed working as expected. I cannot recall my thought process there. Please accept my apologies.
> 
> Re-tested a subset - it's all looking good.

No worries mate, all good 🙂

**Pull request merged**
