### PR TITLE
fix: prompt uses first character of response - allow "yy"

### PR DESCRIPTION
**Pull request by alex-courtis**
follows #2337

### CODE REVIEW

**Comment by Danie-1** [comment]
Maybe using the last character would be more sensible? If I click n and then enter I would expect it to cancel.

**Comment by alex-courtis** [comment]
> Maybe using the last character would be more sensible? If I click n and then enter I would expect it to cancel.

Agreed. See #2377

**Comment by mohamedarish** [comment]
Shouldn't yy and all other things starting with y be accepted?
Having the last character be checked would result in ny["y"]/ns["yes"] being accepted
Not being able to accidentally delete is better than being easily able to accidentally delete

**Comment by alex-courtis** [comment]
> Shouldn't yy and all other things starting with y be accepted?
> Having the last character be checked would result in ny["y"]/ns["yes"] being accepted
> Not being able to accidentally delete is better than being easily able to accidentally delete

Of course. I misread the comment from @Danie-1 , thinking it was first.

Your PR addresses all these concerns.

**Comment by Danie-1** [comment]
I made that comment because I think at one point there was a feature that the letter "y" would be automatically present in the response, and so if we check the first letter I would have to be careful to make sure I delete that letter (because even if I type n then enter, the response would be y). It seems like the prompts have changed though so I don't think the comment is relevant anymore (and maybe it wasn't relevant in the first place and I had just misunderstood how the prompts work).

**Comment by alex-courtis** [comment]
> I made that comment because I think at one point there was a feature that the letter "y" would be automatically present in the response, and so if we check the first letter I would have to be careful to make sure I delete that letter (because even if I type n then enter, the response would be y). It seems like the prompts have changed though so I don't think the comment is relevant anymore (and maybe it wasn't relevant in the first place and I had just misunderstood how the prompts work).

You're right... it wasn't good UX and was the driver of #2377

**Pull request merged**
