### PR TITLE
fix(#2365): make bufname filterable by shada

### PR DESCRIPTION
**Pull request by JosefLitos**
https://github.com/nvim-tree/nvim-tree.lua/discussions/2365

### CODE REVIEW

**Comment by alex-courtis** [comment]
Many thanks for the contribution. I'll get to this on the weekend.

**Comment by alex-courtis** [comment]
Thank you for your contribution, however please accept my apologies @JosefLitos : we won't implement this.

On reflection:
* `:help nvim-tree-api.tree.is_tree_buf()` needs to be fixed
* `utils.is_nvim_tree_buf` needs to be fixed and all its usages audited
* Users do rely on the naming without using the API e.g. https://github.com/nvim-tree/nvim-tree.lua/wiki/Auto-Close

I don't think this change is worth the risk as the blast radius is large.

My [unscientific measurements](https://github.com/nvim-tree/nvim-tree.lua/discussions/2365#discussioncomment-6711350) indicated nvim-tree occupies ~0.25 of the shada history sections and is not overwhelming them.

**Comment by JosefLitos** [comment]
I understand. I haven't considered what losing the path in bufname would cause (although that part could be easily fixed). Anyway, thank you for considering the change.

**Comment by alex-courtis** [comment]
> I understand. I haven't considered what losing the path in bufname would cause (although that part could be easily fixed, but I suppose the prefix is the main issue). Anyway, thank you for considering the change.

Thank you for your understanding and your efforts.

**Pull request closed without merging**
