### PR TITLE
feat: add winid parameter for api.tree.open, toggle, find_file

### LINKED ISSUE #2189: api.tree.open target_window
Background #2173 

Aerial added `aerial.open_in_win` https://github.com/stevearc/aerial.nvim/issues/248 allowing the user to specify a target window instead of opening a new one via the usual rules.

Add similar functionality to nvim-tree.

Allows new workflow e.g.
* create windows for aerial and nvim-tree
* open aerial in one
* open nvim-tree in the other

This is necessary as nvim does not allow window repositioning outside of rows/columns.

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #2189

### CODE REVIEW

**Comment by alex-courtis** [comment]
@mrjones2014  I would be most grateful if you tested this branch: open, toggle, find_file

**Comment by alex-courtis** [comment]
Here's a recipe for managing a leftmost nvim-tree above and aerial below.

I'd be grateful if you could test drive / refine this @mrjones2014 

It needs some tweaking to get aerial and nvim-tree playing nicely with width.

```lua
vim.keymap.set("n", "<space>e", function()
  -- just focus tree if it's visible
  if api.tree.is_visible() then
    api.tree.focus()
    return
  end

  -- scratch buffer to create the new window
  local scratch_bufnr = vim.api.nvim_create_buf(false, true)

  -- find the aerial window
  local aerial_winid = first_winid("aerial")
  local new_winid
  if aerial_winid then
    -- focus aerial
    vim.api.nvim_set_current_win(aerial_winid)

    -- create a horizontal split above
    vim.cmd("aboveleft sbuffer " .. scratch_bufnr)
    new_winid = vim.api.nvim_get_current_win()
  else
    -- create a full height leftmost vertical split
    vim.cmd("topleft vertical sbuffer " .. scratch_bufnr)
    new_winid = vim.api.nvim_get_current_win()
  end

  -- open the tree
  api.tree.open({ winid = new_winid })

  -- delete the scratch buffer
  vim.api.nvim_buf_delete(scratch_bufnr, { force = true })
end, { noremap = true })

vim.keymap.set("n", "<space>j", function()
  -- just focus aerial if it's visible
  local aerial_winid = first_winid("aerial")
  if aerial_winid then
    aerial.focus()
    return
  end

  -- source window, current
  local source_winid = vim.api.nvim_get_current_win()

  -- scratch buffer to create the new window
  local scratch_bufnr = vim.api.nvim_create_buf(false, true)

  local new_winid
  if api.tree.is_visible() then
    -- focus nvim-tree
    api.tree.focus()

    -- create a horizontal split below
    vim.cmd("belowright sbuffer " .. scratch_bufnr)
    new_winid = vim.api.nvim_get_current_win()
  else
    -- create a full height leftmost vertical split
    vim.cmd("topleft vertical sbuffer " .. scratch_bufnr)
    new_winid = vim.api.nvim_get_current_win()
  end

  -- open aerial
  aerial.open_in_win(new_winid, source_winid)

  -- delete the scratch buffer
  vim.api.nvim_buf_delete(scratch_bufnr, { force = true })
end, { noremap = true })
```

**Comment by mrjones2014** [comment]
This is almost exactly what I want 🙂   Is this something that will be built-in to nvim-tree or something?

The only things I'd want different from this are:

- I'd want it on the right side instead of left
- I'd also want a separate buffer list component above nvim-tree

**Comment by alex-courtis** [comment]
> This is almost exactly what I want slightly_smiling_face Is this something that will be built-in to nvim-tree or something?

No. API and a recipe are sufficient. Some convenience API could be added but needs some thought. Perhaps retrieving winid.

We could add open-nvim-tree-somewhere to nvim-tree however it doesn't really help, as the user would need to write their open-something-else anyway.

> The only things I'd want different from this are:
> 
>     * I'd want it on the right side instead of left

You are empowered to place it wherever you like :)

>     * I'd also want a separate buffer list component above nvim-tree

I wanted that once, however my workflow now is sufficient:
* `nvim-tree.renderer.highlight_opened_files`
* "Next/Prev Opened" `api.node.navigate.opened.next` `api.node.navigate.opened.prev`
* "Toggle No Buffer" `api.tree.toggle_no_buffer_filter`

I'll enable the filter depending on the nature of the project I'm working on. I tend to use lsp navigation which populates the opened files.

**Pull request merged**
