### PR TITLE
feat: add `NormalFloat` hl for floating windows

### PR DESCRIPTION
**Pull request by jamestansx**
Currently, `NvimTreeNormal` is used for floating window's background. However, when `winblend` is set and `Normal` highlight is set to transparent, the background will turn `black`. Using `NormalFloat` allows users to customize the background and not interfere with normal window.

<details>
<summary>minimal init.lua</summary>

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      --"jamestansx/nvim-tree.lua",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      { "catppuccin/nvim", as = "catppuccin" }
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true
vim.opt.winblend = 10

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
---@diagnostic disable-next-line: duplicate-set-field
_G.setup = function()
  -- run help with `g?` key or enable float
  -- to see the background color in black
  require("nvim-tree").setup {}

  require("catppuccin").setup({
    transparent_background = true, -- to set Normal to transparent
    integrations = {
      nvimtree = false, -- to ensure that no hl is changed by catppuccin
    }
  })
  vim.cmd.colorscheme "catppuccin"
end

```

</details>

### CODE REVIEW

**Comment by alex-courtis** [comment]
There's a regression with the sign column. Tested under 0.8.3

master:



branch:

**Comment by alex-courtis** [comment]
I'm aware of some breaking changes for floating window backgrounds under nvim 0.9.0.

Parity between branch and master under 0.9.0 is good enough.

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Looking good; we need to ensure default behaviour is unchanged.

**Comment by jamestansx** [comment]
Noted, I have fixed it. You can refer to the following screenshots.

SignColumn:
image

Help window:
image

Float Window:
image

**Review by alex-courtis — APPROVED** [review]
Many thanks for your contribution

**Pull request merged**
