### PR TITLE
docs: add disclaimer for disabling netrw

### PR DESCRIPTION
**Pull request by howarddo2208**
I was confused how my `gx` key bind didn't work, but couldn't find it stated in the docs. Instead, I need to read through the issue section. So, I added these for later users who will be in the same situation as I was.

### CODE REVIEW

**Comment by gegoune** [comment]
There is way more functionality lost when disabling netrw. Not sure we should/can list everything here. Maybe some more generic link to netrw help/features instead?

**Comment by alex-courtis** [comment]
I wish netrw would just Go Away. The decision to remove it is stuck in decision-by-committee.

> Maybe some more generic link to netrw help/features instead?

That would be good, especially from the perspective of a user who actually gains value from it.

**Comment by howarddo2208** [comment]
I just edited the disclaimer to look more general and added the link to netrw docs. Is it ok to merge now?

**Comment by alex-courtis** [comment]
I don't want to pollute the readme or quickstart; netrw is a very niche feature that few actually use.

I've given it a section at the end of the help: #2222

Please review @howarddo2208

**Comment by alex-courtis** [comment]
Resolved via #2222

**Pull request closed without merging**
