### PR TITLE
ci: ubuntu packages -> luarocks action, pin versions

### PR DESCRIPTION
**Pull request by alex-courtis**
Brings in line with https://github.com/nvim-tree/nvim-web-devicons/pull/341

* versions pinned
* avoids ubuntu packages

### CODE REVIEW

**Review by Akmadan23 — APPROVED** [review]
Awesome

**Comment by Akmadan23** [comment]
Not sure why there are these standalone `luackeck` and `stylua` checks here...

**Comment by alex-courtis** [comment]
> Not sure why there are these standalone `luackeck` and `stylua` checks here...

Do you mean two jobs instead of one? I'm not sure either; it seems to be the pattern people follow.

The only reason I can think of is to prevent cross-contamination between jobs.

**Comment by Akmadan23** [comment]
> Do you mean two jobs instead of one? I'm not sure either; it seems to be the pattern people follow.

I mean that besides the three `CI / *` jobs, there are two named respectively `luacheck` and `stylua` with the "Expected - Waiting for status to be reported" label, which prevent me from merging the PRs (any PR after this has this problem)

**Comment by gegoune** [comment]
@Akmadan23 It should be fixed now. :)

**Comment by Akmadan23** [comment]
> It should be fixed now. :)

Thanks! What was the matter?

**Comment by gegoune** [comment]
Required checks are set in branch protection (settings), it still had old jobs configured as required.

**Comment by alex-courtis** [comment]
> Required checks are set in branch protection (settings), it still had old jobs configured as required.

Many thanks!

**Pull request merged**
