### PR TITLE
feat: add option to sort entries in help window

### PR DESCRIPTION
**Pull request by Akmadan23**
Just an option that is nice to have

### CODE REVIEW

**Review by alex-courtis — APPROVED** [review]
Works beautifully. I think I'll enable this one....

Could we go one step further and add a mapping to the window to cycle sort methods?

**Comment by Akmadan23** [comment]
The only minor issue is that the keymap is hardcoded (just like `q` to quit), not sure if it's worth to give the user a way to customize them.

**Comment by alex-courtis** [comment]
Works beautifully, no stray buffers.

> The only minor issue is that the keymap is hardcoded (just like `q` to quit), not sure if it's worth to give the user a way to customize them.

I think that's fine; it's very clear what the mappings are and they are mnemonics.

**Comment by alex-courtis** [comment]
Now that we have the clear mapping do we need the `help.sort_by` option?

We have too many options already...

**Comment by Akmadan23** [comment]
> Now that we have the clear mapping do we need the `help.sort_by` option?

Well, the option can still be useful for those (like me) that don't mind changing the sorting method each time but rather have the preferred one active by default.

**Comment by alex-courtis** [comment]
> Well, the option can still be useful for those (like me) that don't mind changing the sorting method each time but rather have the preferred one active by default.

That's fair enough; it is something that is used frequently. We can remove or refactor if needed.

I've also got a half formed idea of executing commands that may need a help config.

**Review by alex-courtis — APPROVED** [review]

**Review by alex-courtis — APPROVED** [review]
Fantastic work as always!

**Pull request merged**
