### PR TITLE
feat(view): add filters.git_clean, filters.no_buffer

### LINKED ISSUE #1692: can add buffer list like coc-explorer
can add buffer list like coc-explorer

coc

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #1692

```help
    *nvim-tree.filters.git_clean*
    Do not show files with no git status. This will show ignored files when
    |nvim-tree.git.ignore| is set, as they are effectively dirty.
    Toggle via the `toggle_git_clean` action, default mapping `C`.
      Type: `boolean`, Default: `false`

    *nvim-tree.filters.no_buffer*
    Do not show files that have no listed buffer.
    Toggle via the `toggle_no_buffer` action, default mapping `B`.
      Type: `boolean`, Default: `false`
```

no_buffer's matching is a bit fuzzy and may miss some updates on buffer delete/wipe however it is not worth the performance cost of making it perfectly accurate.

- [ ] ~~`filters.diagnostics_ok`~~

Raised #1785 which may be completed separately.

### CODE REVIEW

**Comment by alex-courtis** [comment]
Awaiting test via #1692

**Comment by gegoune** [comment]
Very nice @alex-courtis! I have noticed that after filtering by open buffers only I get plenty of errors repeating constantly, reported and related to Noice. Not sure if that is problem with nvim-tree or Noice.

```
noice.nvim ...ack/packer/start/noice.nvim/lua/noice/view/scrollbar.lua:78: attempt to index field 'thumb' (a nil value) 
noice.nvim ...ack/packer/start/noice.nvim/lua/noice/view/scrollbar.lua:72: attempt to index field 'bar' (a nil value)   
```

Regardless, this is a very welcomed functionality!

**Comment by alex-courtis** [comment]
Thanks for poking at this!

> I have noticed that after filtering by open buffers only I get plenty of errors repeating constantly, reported and related to Noice. Not sure if that is problem with nvim-tree or Noice.

Interesting... I couldn't replicate with the default config with nvim-notify and nui. Any hints?

I do note "Highly Experimental" and some annoying popup flashes when executing `:something` commands from mappings.

Regardless, it would be good to get to the bottom of this as it's likely a real problem.

**Comment by gegoune** [comment]
It works just fine without noice (and with `vigoux/notifier.nvim`). Perhaps @folke could kindly assist (apologies for impolite mention)?

**Comment by folke** [comment]
@gegoune no worries :) I think I just fixed that problem. Would be great if you could confirm.

**Comment by gegoune** [comment]
@folke Thank you very much! It does indeed work now without any errors being logged. Hero! :)

**Comment by alex-courtis** [comment]
Wow so quick, thank you @folke

**Comment by alex-courtis** [comment]
I might just finish diagnostics and release.

New functionality is basically hidden behind the "feature flags" of the actions so no existing functionality should be affected.

**Pull request merged**
