### PR TITLE
feat: remove, copy, trash, bulk delete prompts default to "yes"

### PR DESCRIPTION
**Pull request by xundaoxd**

### CODE REVIEW

**Review by alex-courtis — CHANGES_REQUESTED** [review]
This is a fantastic idea! Many thanks for your contribution.

- [x] Please apply the same to each of these other: copy, trash, bulk delete
- [ ] ~~When `select_prompts = true,` the default is not applied~~

**Comment by xundaoxd** [comment]
@alex-courtis I update the code. use first option as default in vim.ui.input

**Comment by alex-courtis** [comment]
> @alex-courtis I rewrite the code. Use the first option as default in lib.prompt when select_prompts = false

That's really nice!

I'm happy to leave `select_prompts` alone; users of that likely have their own select plugin.

**Review by alex-courtis — APPROVED** [review]
Many thanks for your contribution

**Pull request merged**
