### PR TITLE
feat: support vim.diagnostic.is_disabled()

### PR DESCRIPTION
**Pull request by sstallion**
This PR adds support for checking `vim.diagnostic.is_disabled()` on nvim 0.9+. This function was added to support globally enabling or disabling diagnostics. This is especially useful for setups where diagnostics are enabled conditionally or on a project basis. There is no change in behavior for versions prior to 0.9.

Thanks for a great plugin!

### CODE REVIEW

**Review by alex-courtis — APPROVED** [review]
Works nicely. We don't get a `DiagnosticChanged` event until switching buffers or writing, but that's Good Enough: the tree is refreshed reasonably quickly.

Many thanks for your contribution.

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Please resolve styling issue.

**Comment by sstallion** [comment]
Done. Thanks again!

**Comment by sstallion** [comment]
I wonder if adding the following autocommands (from `lsp.txt`) would be enough:
```
autocmd User LspProgressUpdate redrawstatus
autocmd User LspRequest redrawstatus
```
I'll play around with this a bit today to see if this can close the gap.

**Comment by alex-courtis** [comment]
> I'll play around with this a bit today to see if this can close the gap.

That would be great, thank you. Instant updates would look great.

**Comment by sstallion** [comment]
> That would be great, thank you. Instant updates would look great.

I've been looking into this, this evening and it looks like updates may already be instant. After `from_nvim_lsp()` is called, signs will be cleared, which should achieve the desired result.

Would it be okay to merge this PR as-is? I'm not seeing much else that can be done to improve the responsiveness at this point.

**Comment by alex-courtis** [comment]
> Would it be okay to merge this PR as-is? I'm not seeing much else that can be done to improve the responsiveness at this point.

That's fine. The UX is great.

**Review by alex-courtis — APPROVED** [review]
Many thanks for your contribution.

**Comment by sstallion** [comment]
My pleasure. Thanks for a great plugin!

**Pull request merged**
