### PR TITLE
feat: add kind param to vim.ui.select function calls

### PR DESCRIPTION
**Pull request by devansh08**
This PR adds the optional `kind` parameter to the `vim.ui.select` function calls.

Having this parameter set to something will help in differentiating the `ui.select` prompts of `nvim-tree` from other sources (like LSP code actions or other plugins). This can help in more finer configurations at the user's end. As an example, with this setup I can configure `nvim-tree`'s select prompts to use the relative to cursor telescope theme, while all other prompts can follow the vertical dropdown telescope theme as default.

This does not create any changes in the UI. It only uses an optional parameter that is already present in the `vim.ui` API for this sort of finer configuration.

I'm open to changing/discussing the values I've used here. Something more generic (like `nvimtree_action`) or maybe more specific would be fine as well. For my usage, just having some value that tells me its from `nvim-tree` works.

For reference, the docs of `vim.ui.select` that reference `kind`:

```vimdoc
:help vim.ui.select
...
      • {opts}       (table) Additional options
                     • prompt (string|nil) Text of the prompt. Defaults to
                       `Select one of:`
                     • format_item (function item -> text) Function to format
                       an individual item from `items`. Defaults to
                       `tostring`.
                     • kind (string|nil) Arbitrary hint string indicating the
                       item shape. Plugins reimplementing `vim.ui.select` may
                       wish to use this to infer the structure or semantics of
                       `items`, or the context in which select() was called.
...
```

Do let me know your thoughts on this. Thanks!

### CODE REVIEW

**Comment by alex-courtis** [comment]
This is fantastic, many thanks for identifying this functionality.

Let's apply it to all places:
```
╭──────────────────────────────────────────────────────────────────────────────────── LSP References ────────────────────────────────────────────────────────────────────────────────────╮╭─────
│>                                                                                                                                                                                  5 / 5││  if 
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯│    n
╭──────────────────────────────────────────────────────────── /home/alex/src/nvim-tree/fix/hijack_cursor-with-update-focused ────────────────────────────────────────────────────────────╮│    r
│> lua/nvim-tree/actions/fs/copy…▏      lib.prompt(prompt_input, prompt_select, { "", "y", "n" }, { "Rename", "Yes", "No" }, function(item_short)                                        ││  end
│  lua/nvim-tree/actions/fs/remo…▏    lib.prompt(prompt_input, prompt_select, items_short, items_long, function(item_short)                                                              ││     
│  lua/nvim-tree/actions/fs/tras…▏    lib.prompt(prompt_input, prompt_select, items_short, items_long, function(item_short)                                                              ││  loc
│  lua/nvim-tree/marks/bulk-dele…▏    lib.prompt(prompt_input, prompt_select, { "", "y" }, { "No", "Yes" }, function(item_short)                                                         ││    s
│  lua/nvim-tree/marks/bulk-tras…▏    lib.prompt(prompt_input, prompt_select, { "", "y" }, { "No", "Yes" }, function(item_short)                                                         ││    i
│                                                                                                                                                                                        ││     
```

**Comment by alex-courtis** [comment]
We need to document this. Please insert a new help section 10 nvim-tree-prompts

Don't be overly concerned about the text - I'll help out once you've got a draft in place.

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Many thanks for your contribution:

- [ ] all prompts
- [ ] doc

**Comment by devansh08** [comment]
Done with the requested code changes.

I've also created the help section for prompts. Do let me know if you think it needs any changes (content or formatting). This is my first time writing vim documentation, so I may have missed out on some syntax (Apologies in advance, if so :) ).

**Comment by alex-courtis** [comment]
> Done with the requested code changes.
> 
> I've also created the help section for prompts. Do let me know if you think it needs any changes (content or formatting). This is my first time writing vim documentation, so I may have missed out on some syntax (Apologies in advance, if so :) ).

That's great, tidied a bit and added underscores.

**Review by alex-courtis — APPROVED** [review]
Many thanks for your contribution!

**Pull request merged**
