### PR TITLE
chore: remove pngs from .github folder and use direct links for imgs in README.md

### PR DESCRIPTION
**Pull request by Almo7aya**
+ added a screenshot for nvim-tree in floating window mode

### CODE REVIEW

**Comment by gegoune** [comment]
Please don't commit images to repository. Media files should be added to an issue and linked from there to avoid users having to download those files while installing plugin.

**Comment by Almo7aya** [comment]
> Please don't commit images to repository. Media files should be added to an issue and linked from there to avoid users having to download those files while installing plugin.

Yes you are right, added it in .github to follow the other screenshots locations, I think we should move them all

**Comment by Almo7aya** [comment]
I'll remove the pngs from .github folder and upload them here to this PR, and use their links in the README.md

**Comment by Almo7aya** [comment]
<details>
<summary>Screenshots</summary>
example help
example tree
screenshot-alex-courtis
screenshot
screenshot2
screenshot3
screenshot4
screenshot-almo7aya

</details>

**Comment by gegoune** [comment]
Thank you very much @Almo7aya. I have envisioned new issue called `Showcase` where users could upload their screenshots, we could update readme links if something beautiful comes up. Would you mind recreating your last post here as a new issue? GitHub does not allow us to create new issue of comment, just to reference it.

Maybe craete new issue with only existing images in it, then add new comment with your new images and update that pr accordingly?

**Comment by kyazdani42** [comment]
or a wiki page

**Comment by gegoune** [comment]
That's probably even better.

**Comment by Almo7aya** [comment]
I created a wiki page https://github.com/nvim-tree/nvim-tree.lua/wiki/Showcases with all the pngs in the .github folder, newly added screenshots should be uploaded there and use their links in the README.md file if we are planning to keep them there

**Review by gegoune — APPROVED** [review]

**Comment by alex-courtis** [comment]
> 

Thanks @Almo7aya 

We should just link that wiki page at the bottom of the readme.

**Comment by alex-courtis** [comment]
> I created a wiki page https://github.com/nvim-tree/nvim-tree.lua/wiki/Showcases with all the pngs in the .github folder, newly added screenshots should be uploaded there and use their links in the README.md file if we are planning to keep them there

Can you please add a link you your setup lua source @Almo7aya ? Others will likely want to clone bits of it.

I've done that with a link to the specific commit for my `nvim-tree.lua` above the image.

**Comment by Almo7aya** [comment]
@alex-courtis I'm using https://github.com/lunarvim/lunarvim/ so my config is tied to their implementation, I'll create a standalone config for it and add it to the wiki page

**Pull request merged**
