### PR TITLE
fix(#2862): windows path replaces backslashes with forward slashes

### LINKED ISSUE #2862: Wrong filepath opened when selecting file
### Description

I am unable to open a file and read it because nvim-tree, when selecting a file, will open a nonexistent file. The route it should be opening should be `\app\(pages)\(app)\document\[id]\page.tsx` but instead opens `\app(pages)(app)\document\[id]\page.tsx`. I don't seem to have this issue with other plugins such as telescope, where I can use the file finder and it will give me a preview of the content (I will provide an image below). My guess is when it tries to put a backslash before a parenthesis, it registers it as just a parenthesis (kind of how in regex you have to put a backslash before some characters).

# Incorrect Path
image

# Telescope Displaying Content Correctly
image

### Neovim version

```text
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
```

### Operating system and version

Windows 11

### Windows variant

_No response_

### nvim-tree version

v1.5.0 (latest)

### Clean room replication

```lua
I am a bit confused about this step, but you can find my neovim setup here:
https://github.com/LandonHarter/neovim/master
```

### Steps to reproduce

1. Create a directory that starts and ends with parenthesis (maybe try nesting a few together like mine in the photo)
2. Create a file in one of the new directories
3. Try to open the file with nvim-tree

### Expected behavior

Opens the file

### Actual behavior

Tries to open a nonexistent file leading to me being unable to edit the file

### PR DESCRIPTION
**Pull request by dogeggz**
### Changes:
- Replaces `\` with `/` in file paths for Windows.
- Applies the updated path handling to functions that use the filename (e.g. open, open in tab, split, etc.).

### Note:
- Verified that all filename-related tasks work fine on my Windows machine.
- Not sure if this change will affect anything else though.

### CODE REVIEW

**Review by alex-courtis — APPROVED** [review]
Many thanks for your contribution, this looks reasonable.

It looks like all changes are hidden behind the appropriate OS feature flag, thank you.

nvim-tree developers don't have access to or expertise with windows, hence can't test this.

Please be prepared to quickly resolve any issues that may arise from this change. nvim-tree developers will have no option but to roll it back.

**Review by alex-courtis — CHANGES_REQUESTED** [review]
This slash change is quite far-reaching and may result in difficulties for various configurations.

Please verify this change on the [variants of windows](https://github.com/nvim-tree/nvim-tree.lua/wiki/Development#os-feature-flags):

- [ ] WSL
- [ ] powershell
- [ ] nvim-qt

Cygwin / msys2 would be great, however I believe their setup is difficult and there are few users, so I'm happy to take a risk.

- [x] Please resolve the luals check failures. Setting up [lua language server](https://github.com/nvim-tree/nvim-tree.lua/wiki/Development#lua-language-server) will assist you.

**Comment by dogeggz** [comment]
I verified the file-opening tasks on all three variants, and everything works fine on my end。

**Review by alex-courtis — APPROVED** [review]

**Comment by alex-courtis** [comment]
Many thanks for your contribution @dogeggz

**Pull request merged**
