### PR TITLE
fix(#2774): add winfixbuf view option for nvim 0.10

### PR DESCRIPTION
**Pull request by petobens**
Hi @alex-courtis I've only added the option for the View class. Dunno if this is useful/needed elsewhere. Feel free to modify the PR as you deem fit.

### CODE REVIEW

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Looking good; this should greatly simplify things.

We are going to have to be careful: 0.10 is not stable and there will be unforseen consequences, due to existing assumptions and workarounds.

Please:
* Put this behind an experiment opt in "feature flag": `:h nvim-tree-opts-experimental`
* Disable `_prevent_buffer_override` and all the other workarounds in place that currently achieve winfixbuf functionality

Update help etc. etc.

**Comment by alex-courtis** [comment]
@petobens we're officially supporting release 0.10 now.

Can you please continue with this PR with the experimental guards in place?

**Comment by petobens** [comment]
Hi @alex-courtis, unfortunately I won't be able to followup this in the short term.  Feel free to continue it if you deem fit (otherwise I'll revisit it in the next months).

**Comment by alex-courtis** [comment]
> Hi @alex-courtis, unfortunately I won't be able to followup this in the short term. Feel free to continue it if you deem fit (otherwise I'll revisit it in the next months).

No worries at all. Your contributions are welcome whenever you have the time.

**Comment by kutsan** [comment]
What will be the status of the feature now that the issue is closed?

**Comment by alex-courtis** [comment]
> What will be the status of the feature now that the issue is closed?

Still open. Waiting on a kind contributor.

**Comment by emmanueltouzery** [comment]
Otherwise from a user point of view, nvim-tree support is not really needed. I just have this in my config and it works great:
```lua
-- winfixbuf
if vim.fn.has("nvim-0.10") == 1 then
  vim.api.nvim_create_autocmd("BufEnter", {
    callback = function()
      if vim.list_contains({"NvimTree", "OverseerList", "aerial", "toggleterm", "dbui", "dbout"}, vim.bo.filetype) then
        vim.wo.winfixbuf = true
      end
    end,
  })
end
```

But I guess it would be handier if nvim-tree had it built-in.

**Pull request closed without merging**
